# Generated by Django 5.0 on 2024-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplaintCategory', models.CharField(max_length=100, null=True)),
                ('ComplaintName', models.CharField(max_length=100, null=True)),
                ('ComplaintLocation', models.CharField(max_length=100, null=True)),
                ('ComplaintDistrict', models.CharField(max_length=100, null=True)),
                ('ComplaintPincode', models.IntegerField(null=True)),
                ('ComplaintDes', models.TextField(null=True)),
            ],
        ),
    ]
