# Generated by Django 5.0 on 2024-03-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0001_initial'),
        ('signup', '0010_remove_signup_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.signup'),
        ),
    ]
