# Generated by Django 5.0 on 2024-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0002_complaints_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='ComplaintImage',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
