# Generated by Django 5.0 on 2024-03-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0007_signup_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Officer_mail', models.CharField(max_length=100)),
                ('Officer_password', models.CharField(max_length=100)),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup')),
            ],
        ),
    ]
