# Generated by Django 5.0 on 2024-03-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
