# Generated by Django 5.0 on 2024-03-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_signup_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnetimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_numbers', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='otp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.onetimepassword'),
        ),
    ]
