# Generated by Django 5.0 on 2024-03-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_onetimepassword_alter_signup_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='otp',
        ),
        migrations.DeleteModel(
            name='OnetimePassword',
        ),
    ]
