# Generated by Django 5.0 on 2024-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_remove_signup_name_signup_fname_signup_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
