# Generated by Django 5.0 on 2024-03-22 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Officer', '0002_remove_officer_registered_user'),
        ('signup', '0007_signup_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Officer.officer'),
        ),
    ]
